name: pytest

on:
  push:
    branches:
      - main  # Your branch name
    paths:
      - '**/*.py'  # Trigger only for changes in Python files
  pull_request:
    branches:
      - main  # Your branch name
    paths:
      - '**/*.py'  # Trigger for changes in Python files

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This checks out your code to the runner

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3  # Sets up the specified Python version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
	python -m pip install -r requirements-github.txt  # Install dependencies from requirements.txt


    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest --cov=SuomiGeoData --cov-report=xml  # Run tests and generate coverage report in XML format
